
package el_corte_ingles;

import el_corte_ingles.ConexionmMySQL;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.util.Date;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Usuario
 */
public class Crud_BBDD extends javax.swing.JFrame {

    //Conectamos con la base de datos y establecemos nuestra tabla
    ConexionmMySQL con = new ConexionmMySQL();
    Connection conexion = con.ConexionmMySQL();
    
    
    
    //Declaramos variables
    int idc;
    int idv;
    
    
    public Crud_BBDD() {
        initComponents();
        setLocationRelativeTo(null);
        //Conectamos con la BBDD
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtEdad = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtContrato = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtInicioC = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtFinalC = new javax.swing.JTextField();
        txtPlanta = new javax.swing.JTextField();
        txtIdP = new javax.swing.JTextField();
        txtBuscar = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_BBDD = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        btn_limpiar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        Personal1 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(680, 624));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos"));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("ID_Personal : ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 80, -1));

        jLabel5.setText("Edad :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));
        jPanel1.add(txtEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 80, -1));

        jLabel6.setText("Nombre :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, -1, -1));

        jLabel9.setText("Planta :");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, -1, -1));
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 20, 160, -1));

        jLabel4.setText("Contrato :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));
        jPanel1.add(txtContrato, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 100, -1));

        jLabel7.setText("Fecha_Inicio_Contrato :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, -1, -1));

        txtInicioC.setToolTipText("");
        txtInicioC.setName(""); // NOI18N
        jPanel1.add(txtInicioC, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 70, 90, -1));
        txtInicioC.getAccessibleContext().setAccessibleName("as");
        txtInicioC.getAccessibleContext().setAccessibleDescription("ds");

        jLabel8.setText("Fecha_Final_Contrato :");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 70, -1, -1));

        txtFinalC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFinalCActionPerformed(evt);
            }
        });
        jPanel1.add(txtFinalC, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 70, 80, -1));
        jPanel1.add(txtPlanta, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, 80, -1));
        jPanel1.add(txtIdP, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 50, -1));
        jPanel1.add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 120, 80, -1));

        jLabel10.setText("Buscar :");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 120, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 620, 160));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable_BBDD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID_Personal", "ID_Venta", "Nombre", "Contrato", "Fecha_Inicio_Contrato", "Fecha_Final_Contrato", "Edad", "Planta"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_BBDD.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        jTable_BBDD.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        jTable_BBDD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_BBDDMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_BBDD);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 160));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 620, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Acciones"));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_limpiar.setText("Limpiar");
        btn_limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_limpiarActionPerformed(evt);
            }
        });
        jPanel2.add(btn_limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 40, 100, 60));

        jButton2.setText("Agregar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 80, 60));

        jButton3.setText("Eliminar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 80, 60));

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        jPanel2.add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 40, 90, 60));

        Personal1.setText("Mostrar");
        Personal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Personal1ActionPerformed(evt);
            }
        });
        jPanel2.add(Personal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 40, 90, 60));

        jButton5.setText("Modificar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, 90, 60));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 620, 150));

        jLabel1.setText("Acceso Base de Datos");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, -1, -1));

        jButton6.setText("Cerrar la Aplicación");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 550, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        insertar(txtIdP,txtNombre,txtContrato,txtInicioC,txtFinalC,txtEdad,txtPlanta);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
        eliminar();
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
       
        //Actualizamos campos de la BBDD por lo escrito en los TextField
        try {
            //Escribimos consulta
            PreparedStatement pps = conexion.prepareStatement("UPDATE personal SET ID_Personal='"+txtIdP.getText()+"',Nombre='"+txtNombre.getText()+"',Contrato='"+txtContrato.getText()+"',Fecha_Inicio_Contrato='"+txtInicioC.getText()+"',Fecha_Final_Contrato='"+txtFinalC.getText()+"',Edad='"+txtEdad.getText()+"',Planta='"+txtPlanta.getText()+"'WHERE ID_Personal='"+txtBuscar.getText()+"'");
            //Actualizamos base de datos
            pps.executeUpdate();
            //Mensaje correcta actualización
            JOptionPane.showMessageDialog(null, "Datos actualizados");
            
        } catch (SQLException ex) {
            Logger.getLogger(Crud_BBDD.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btn_limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_limpiarActionPerformed

        //Limpiamos los campos
        txtIdP.setText("");
        txtNombre.setText("");
        txtContrato.setText("");
        txtInicioC.setText("");
        txtFinalC.setText("");
        txtEdad.setText("");
        txtPlanta.setText("");
        txtBuscar.setText("");
    }//GEN-LAST:event_btn_limpiarActionPerformed

    private void jTable_BBDDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_BBDDMouseClicked
      
    }//GEN-LAST:event_jTable_BBDDMouseClicked

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        
        //Seguro antes de salir
        String[] botones = {"SI", "NO"};
        int opcion = JOptionPane.showOptionDialog(null, "Seguro que quiere cerrar la aplicación?", "Cerrar Aplicación", 0, JOptionPane.QUESTION_MESSAGE, null, botones, "SI");

        if (opcion == 0) {
            System.exit(0);
        } else {
            JOptionPane.showMessageDialog(null, "Gracias por no cerrar la aplicación");
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void txtFinalCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFinalCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFinalCActionPerformed

    private void Personal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Personal1ActionPerformed
        mostrar("personal");
    }//GEN-LAST:event_Personal1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        modificar();
    }//GEN-LAST:event_jButton5ActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Crud_BBDD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Crud_BBDD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Crud_BBDD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Crud_BBDD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Crud_BBDD().setVisible(true);
            }
        });
    }

    public void mostrar(String tabla){
        
        //Método usado para mostrar los datos en la tabla, guardamos consult en la variable
        String sql = "SELECT * FROM " +tabla;
        Statement st;
        
        //Crea objeto DefaultTableModel y añade columnas correspondientes:
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Id_Personal");
        model.addColumn("Nombre");
        model.addColumn("Contrato");
        model.addColumn("Fecha_Inicio_Contrato");
        model.addColumn("Fecha_Final_Contrato");
        model.addColumn("Edad");
        model.addColumn("Planta");
        
        jTable_BBDD.setModel(model);
        
        
        String [] datos = new String [7];
        
        //En cada posición se guarda cada dato, y luego se muestran en la tabla
        try{
            st = conexion.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while(rs.next()){
                datos[0]=rs.getString(1);
                datos[1]=rs.getString(2);
                datos[2]=rs.getString(3);
                datos[3]=rs.getString(4);
                datos[4]=rs.getString(5);
                datos[5]=rs.getString(6);
                datos[6]=rs.getString(7);
             
                model.addRow(datos);
                
            }
           
             
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null,"No se ha podido mostrar" + e.toString());
        }
    }
    
    public void insertar(JTextField ID_Personal,JTextField nombre,JTextField contrato,JTextField Fecha_Inicio_Contrato,JTextField Fecha_Final_Contrato,JTextField Edad,JTextField Planta){
        
        //Método para insertar los datos
        try{
                //Escribimos su correspondiente consulta y en cada campo metemos el texto escrito en los TextFields
                PreparedStatement pps = conexion.prepareStatement("INSERT INTO personal(ID_Personal,Nombre,Contrato,Fecha_Inicio_Contrato,Fecha_Final_Contrato,Edad,Planta) V                   ALUES(?,?,?,?,?,?,?)");
                pps.setString(1, txtIdP.getText());
                pps.setString(2, txtNombre.getText());
                pps.setString(3, txtContrato.getText());
                pps.setString(4, txtInicioC.getText());
                pps.setString(5, txtFinalC.getText());
                pps.setString(6, txtEdad.getText());
                pps.setString(7, txtPlanta.getText());
                //Actualizamos base de datos
                pps.executeUpdate();
                JOptionPane.showMessageDialog(null, "Datos guardados");
                //Llamamos al método mostrar para mostrar la tabla
                mostrar("personal");
                
        }catch(Exception e){
            System.out.println(e + "Error al insertar");
        }
    }

    public void eliminar(){
        
        //Almacenamos la fila seleccionada y le damos un valor pasado a String
        int fila = jTable_BBDD.getSelectedRow();
        String valor = jTable_BBDD.getValueAt(fila, 0).toString();
        
        if(fila>=0){
            //Si se selecciona uno de los campos. se elimina, actualiza y muestra mensaje de éxito 
            try{
            PreparedStatement pps = conexion.prepareStatement("Delete from personal where Id_Personal='" + valor+"'");
            pps.executeUpdate();
            JOptionPane.showMessageDialog(null, "Datos eliminados correctamente");
            mostrar("personal");
        }catch (SQLException e){
             System.out.println(e + "No se ha podido borrar");
        }
        
        
    }
    
    
    }
    
    //Método creado para modificar, especificamente para mostrar en los campos los datos de la fila seleccionada
    public void modificar(){
        int fila = jTable_BBDD.getSelectedRow();
        if(fila>=0){
            txtBuscar.setText(jTable_BBDD.getValueAt(fila,0).toString()) ;
            txtIdP.setText(jTable_BBDD.getValueAt(fila,0).toString());
            txtNombre.setText(jTable_BBDD.getValueAt(fila,1).toString());
            txtContrato.setText(jTable_BBDD.getValueAt(fila,2).toString());
            txtInicioC.setText(jTable_BBDD.getValueAt(fila,3).toString());
            txtFinalC.setText(jTable_BBDD.getValueAt(fila,4).toString());
            txtEdad.setText(jTable_BBDD.getValueAt(fila,5).toString());
            txtPlanta.setText(jTable_BBDD.getValueAt(fila,6).toString());
        }else{
            JOptionPane.showMessageDialog(null, "Fila no seleccionada");
        }
    }
    
    
    public void borrar(JTextField Id_Personal,JTextField nombre,JTextField contrato,JTextField Fecha_Inicio_Contrato,JTextField Fecha_Final_Contrato,JTextField Edad,JTextField Planta){
        //Método para limpiar los campos
        Id_Personal.setText("");
        nombre.setText("");
        contrato.setText("");
        Fecha_Inicio_Contrato.setText("");
        Fecha_Final_Contrato.setText("");
        Edad.setText("");
        Planta.setText("");
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton Personal1;
    private javax.swing.JButton btnActualizar;
    public javax.swing.JButton btn_limpiar;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable jTable_BBDD;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtContrato;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtFinalC;
    private javax.swing.JTextField txtIdP;
    private javax.swing.JTextField txtInicioC;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPlanta;
    // End of variables declaration//GEN-END:variables
}
