
package el_corte_ingles;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.FileWriter;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.LocalDate;
import java.time.LocalTime;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Usuario
 */
public class Pantalla extends javax.swing.JFrame {
    
    //Establecemos la conexion con MySQL y creamos objeto tipo Crud_BBDD
    ConexionmMySQL con = new ConexionmMySQL();
    Connection cn = con.ConexionmMySQL();
    Crud_BBDD objeto_bbdd = new Crud_BBDD();
    
    //Pantalla Crud_BBDD
    Crud_BBDD pantallaCrud = new Crud_BBDD();
    
    //Creamos los ArrayList que van a contener las listas con nuestros poductos
    
    ArrayList<ROPA> Gestion_Ropa = new ArrayList<>();
    ArrayList<CALZADO> Gestion_Calzado = new ArrayList<>();
    ArrayList<MAQUILLAJE> Gestion_Maquillaje= new ArrayList<>();
    ArrayList<ALIMENTACION> Gestion_Alimentacion = new ArrayList<>();
    ArrayList<INFORMATICA> Gestion_Informatica = new ArrayList<>();
    
    
  
    
    /**
     *
     */
    public Pantalla() {
        initComponents();
        setLocationRelativeTo(null);
        
        //Iniciamos el temporizador
        timer.start();
        
        
        //Posicionamineto de pantallas en el centro
         jDialog1.setLocationRelativeTo(null);
         jDialog2.setLocationRelativeTo(null);
         jDialog3.setLocationRelativeTo(null);
         jDialog4.setLocationRelativeTo(null);
         jDialog5.setLocationRelativeTo(null);
         jDialog6.setLocationRelativeTo(null);
         jDialog7.setLocationRelativeTo(null);
         jDialog8.setLocationRelativeTo(null);
         jDialog9.setLocationRelativeTo(null);
         jDialog10.setLocationRelativeTo(null);
         jDialog11.setLocationRelativeTo(null);
         jDialog12.setLocationRelativeTo(null);
         jDialog13.setLocationRelativeTo(null);
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jLabel3 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jDialog2 = new javax.swing.JDialog();
        jLabel6 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jDialog3 = new javax.swing.JDialog();
        jRadioButton2 = new javax.swing.JRadioButton();
        jButton37 = new javax.swing.JButton();
        jButton38 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jDialog4 = new javax.swing.JDialog();
        jRadioButton1 = new javax.swing.JRadioButton();
        jLabel13 = new javax.swing.JLabel();
        jButton16 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jButton20 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jDialog5 = new javax.swing.JDialog();
        jRadioButton3 = new javax.swing.JRadioButton();
        jButton17 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jButton25 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jDialog6 = new javax.swing.JDialog();
        jRadioButton4 = new javax.swing.JRadioButton();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jButton30 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jDialog7 = new javax.swing.JDialog();
        jRadioButton5 = new javax.swing.JRadioButton();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jButton35 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jDialog8 = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jDialog9 = new javax.swing.JDialog();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jDialog10 = new javax.swing.JDialog();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jDialog11 = new javax.swing.JDialog();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jDialog12 = new javax.swing.JDialog();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();
        jDialog13 = new javax.swing.JDialog();
        jLabel21 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jButton39 = new javax.swing.JButton();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jDialog1.setMinimumSize(new java.awt.Dimension(966, 300));
        jDialog1.setPreferredSize(new java.awt.Dimension(1280, 300));
        jDialog1.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Sitka Text", 3, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("PLANTA 0");
        jDialog1.getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 20, 230, -1));

        jButton5.setBackground(new java.awt.Color(0, 204, 0));
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Alimentación");
        jButton5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jDialog1.getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, 90, 30));

        jButton6.setBackground(new java.awt.Color(0, 204, 0));
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Maquillaje");
        jButton6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jDialog1.getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 150, 90, 30));

        jButton7.setBackground(new java.awt.Color(0, 204, 0));
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("Volver al Inicio");
        jButton7.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jDialog1.getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 220, 100, 30));

        jButton8.setBackground(new java.awt.Color(0, 204, 0));
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("Salir de la Aplicación");
        jButton8.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jDialog1.getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 220, 130, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/el_corte_ingles/Alimentacion.png"))); // NOI18N
        jDialog1.getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -60, 560, 370));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/el_corte_ingles/maquillaje.jpg"))); // NOI18N
        jDialog1.getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 0, 720, 260));

        jDialog2.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        jDialog2.setSize(new java.awt.Dimension(857, 295));
        jDialog2.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Sitka Text", 3, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("PLANTA 1");
        jDialog2.getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, 230, -1));

        jButton9.setBackground(new java.awt.Color(0, 204, 0));
        jButton9.setForeground(new java.awt.Color(255, 255, 255));
        jButton9.setText("Ropa");
        jButton9.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jDialog2.getContentPane().add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 80, 30));

        jButton10.setBackground(new java.awt.Color(0, 204, 0));
        jButton10.setForeground(new java.awt.Color(255, 255, 255));
        jButton10.setText("Calzado");
        jButton10.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jDialog2.getContentPane().add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 150, 100, 30));

        jButton11.setBackground(new java.awt.Color(0, 204, 0));
        jButton11.setForeground(new java.awt.Color(255, 255, 255));
        jButton11.setText("Volver al Inicio");
        jButton11.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jDialog2.getContentPane().add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 220, 100, 30));

        jButton12.setBackground(new java.awt.Color(0, 204, 0));
        jButton12.setForeground(new java.awt.Color(255, 255, 255));
        jButton12.setText("Salir de la Aplicación");
        jButton12.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jDialog2.getContentPane().add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 220, 120, 30));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/el_corte_ingles/Ropa.jpg"))); // NOI18N
        jDialog2.getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, -10, 490, 290));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/el_corte_ingles/Calzado.jpg"))); // NOI18N
        jDialog2.getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 0, 410, 270));

        jDialog3.setSize(new java.awt.Dimension(476, 350));
        jDialog3.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jRadioButton2.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButton2.setText("Insertar");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        jDialog3.getContentPane().add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, -1, -1));

        jButton37.setBackground(new java.awt.Color(0, 204, 0));
        jButton37.setForeground(new java.awt.Color(255, 255, 255));
        jButton37.setText("Ver");
        jButton37.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton37ActionPerformed(evt);
            }
        });
        jDialog3.getContentPane().add(jButton37, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 110, 30));

        jButton38.setBackground(new java.awt.Color(0, 204, 0));
        jButton38.setForeground(new java.awt.Color(255, 255, 255));
        jButton38.setText("Eliminar");
        jButton38.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton38ActionPerformed(evt);
            }
        });
        jDialog3.getContentPane().add(jButton38, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 110, 30));

        jButton13.setBackground(new java.awt.Color(0, 204, 0));
        jButton13.setForeground(new java.awt.Color(255, 255, 255));
        jButton13.setText("Volver al Inicio");
        jButton13.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jDialog3.getContentPane().add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, 110, 30));

        jButton14.setBackground(new java.awt.Color(0, 204, 0));
        jButton14.setForeground(new java.awt.Color(255, 255, 255));
        jButton14.setText("Salir de la Aplicación");
        jButton14.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        jDialog3.getContentPane().add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 250, 130, 30));

        jLabel10.setBackground(new java.awt.Color(0, 204, 0));
        jLabel10.setFont(new java.awt.Font("Sitka Text", 3, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("PLANTA 2 (INFORMATICA)");
        jDialog3.getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/el_corte_ingles/informatica.jpg"))); // NOI18N
        jDialog3.getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 480, 320));

        jDialog4.setSize(new java.awt.Dimension(560, 459));
        jDialog4.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jRadioButton1.setText("Insertar");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        jDialog4.getContentPane().add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, -1, -1));

        jLabel13.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("PLANTA 0 (ALIMENTACIÓN)");
        jDialog4.getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 320, -1));

        jButton16.setBackground(new java.awt.Color(0, 204, 0));
        jButton16.setForeground(new java.awt.Color(255, 255, 255));
        jButton16.setText("Ver");
        jButton16.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        jDialog4.getContentPane().add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, 80, 30));

        jButton18.setBackground(new java.awt.Color(0, 204, 0));
        jButton18.setForeground(new java.awt.Color(255, 255, 255));
        jButton18.setText("Eliminar");
        jButton18.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        jDialog4.getContentPane().add(jButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, 80, 30));

        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jDialog4.getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 420, -1, -1));

        jButton20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/el_corte_ingles/salida.jpg"))); // NOI18N
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });
        jDialog4.getContentPane().add(jButton20, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 350, 50, 80));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/el_corte_ingles/Alimentacion.jpg"))); // NOI18N
        jLabel12.setText("jLabel12");
        jDialog4.getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 460));

        jDialog5.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        jDialog5.setSize(new java.awt.Dimension(410, 325));
        jDialog5.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jRadioButton3.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButton3.setText("Insertar");
        jDialog5.getContentPane().add(jRadioButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, -1, -1));

        jButton17.setBackground(new java.awt.Color(0, 204, 0));
        jButton17.setForeground(new java.awt.Color(255, 255, 255));
        jButton17.setText("Ver");
        jButton17.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        jDialog5.getContentPane().add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, 80, 30));

        jButton19.setBackground(new java.awt.Color(0, 204, 0));
        jButton19.setForeground(new java.awt.Color(255, 255, 255));
        jButton19.setText("Eliminar");
        jButton19.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });
        jDialog5.getContentPane().add(jButton19, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 80, 30));

        jLabel16.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("PLANTA 0 (MAQUILLAJE)");
        jDialog5.getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, -1, -1));

        jButton25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/el_corte_ingles/salida.jpg"))); // NOI18N
        jButton25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton25ActionPerformed(evt);
            }
        });
        jDialog5.getContentPane().add(jButton25, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 210, 40, 60));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/el_corte_ingles/maquillaje.jpg"))); // NOI18N
        jDialog5.getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 510, 360));

        jDialog6.setMinimumSize(new java.awt.Dimension(535, 260));
        jDialog6.setSize(new java.awt.Dimension(535, 260));
        jDialog6.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jRadioButton4.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButton4.setText("Insertar");
        jDialog6.getContentPane().add(jRadioButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, -1, -1));

        jButton21.setBackground(new java.awt.Color(0, 204, 0));
        jButton21.setForeground(new java.awt.Color(255, 255, 255));
        jButton21.setText("Ver");
        jButton21.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });
        jDialog6.getContentPane().add(jButton21, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 80, 30));

        jButton22.setBackground(new java.awt.Color(0, 204, 0));
        jButton22.setForeground(new java.awt.Color(255, 255, 255));
        jButton22.setText("Eliminar");
        jButton22.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });
        jDialog6.getContentPane().add(jButton22, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, 80, 30));

        jLabel18.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("PLANTA 1 (ROPA)");
        jDialog6.getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, -1, -1));

        jButton30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/el_corte_ingles/salida.jpg"))); // NOI18N
        jButton30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton30ActionPerformed(evt);
            }
        });
        jDialog6.getContentPane().add(jButton30, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 180, 40, 70));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/el_corte_ingles/Ropa.jpg"))); // NOI18N
        jDialog6.getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 560, 280));

        jDialog7.setSize(new java.awt.Dimension(506, 284));
        jDialog7.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jRadioButton5.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButton5.setText("Insertar");
        jDialog7.getContentPane().add(jRadioButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, -1, -1));

        jButton23.setBackground(new java.awt.Color(0, 204, 0));
        jButton23.setForeground(new java.awt.Color(255, 255, 255));
        jButton23.setText("Ver");
        jButton23.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton23ActionPerformed(evt);
            }
        });
        jDialog7.getContentPane().add(jButton23, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 80, 30));

        jButton24.setBackground(new java.awt.Color(0, 204, 0));
        jButton24.setForeground(new java.awt.Color(255, 255, 255));
        jButton24.setText("Eliminar");
        jButton24.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton24ActionPerformed(evt);
            }
        });
        jDialog7.getContentPane().add(jButton24, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 80, 30));

        jLabel20.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("PLANTA 1 (DEPORTES)");
        jDialog7.getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, -1, -1));

        jButton35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/el_corte_ingles/salida.jpg"))); // NOI18N
        jButton35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton35ActionPerformed(evt);
            }
        });
        jDialog7.getContentPane().add(jButton35, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 170, 50, 70));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/el_corte_ingles/Calzado.jpg"))); // NOI18N
        jDialog7.getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 610, 320));

        jDialog8.setSize(new java.awt.Dimension(960, 180));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID_Alimentacion", "Tipo", "Precio", "Caducidad", "Planta", "Descuento", "Marca"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jDialog8.getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jDialog9.setSize(new java.awt.Dimension(960, 180));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID_Maquillaje", "Nombre", "Tipo", "Precio", "Marca", "Descuento", "Promocion", "Color", "Tono", "Planta", "Descripcion"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jDialog9.getContentPane().add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jDialog10.setSize(new java.awt.Dimension(960, 180));

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID_Ropa", "Nombre", "Tipo", "Precio", "Marca", "Descuento", "Promocion", "Color", "Codigo", "Planta"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        jDialog10.getContentPane().add(jScrollPane3, java.awt.BorderLayout.CENTER);

        jDialog11.setSize(new java.awt.Dimension(960, 180));

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID_Calzado", "Nombre", "Tipo", "Precio", "Marca", "Descuento", "Promocion", "Color", "Codigo", "Planta"
            }
        ));
        jScrollPane4.setViewportView(jTable4);

        jDialog11.getContentPane().add(jScrollPane4, java.awt.BorderLayout.CENTER);

        jDialog12.setSize(new java.awt.Dimension(960, 180));

        jTable5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID_Informatica", "Nombre", "Precio", "Marca", "Descuento", "Planta", "Dispositivo"
            }
        ));
        jScrollPane5.setViewportView(jTable5);

        jDialog12.getContentPane().add(jScrollPane5, java.awt.BorderLayout.CENTER);

        jDialog13.setSize(new java.awt.Dimension(535, 450));
        jDialog13.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel21.setFont(new java.awt.Font("Segoe UI Historic", 0, 36)); // NOI18N
        jLabel21.setText("MODIFICAR ALIMENTACION ");
        jDialog13.getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));
        jDialog13.getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 260, -1));

        jLabel22.setText("ID_Alimento");
        jDialog13.getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, -1, -1));

        jLabel23.setText("Tipo");
        jDialog13.getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, -1, -1));
        jDialog13.getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 260, -1));
        jDialog13.getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 260, -1));

        jLabel24.setText("Precio");
        jDialog13.getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, -1, -1));

        jButton39.setText("MODIFICAR");
        jButton39.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton39ActionPerformed(evt);
            }
        });
        jDialog13.getContentPane().add(jButton39, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 390, -1, -1));
        jDialog13.getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 260, -1));
        jDialog13.getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, 260, -1));
        jDialog13.getContentPane().add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, 260, -1));
        jDialog13.getContentPane().add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 340, 260, -1));

        jLabel25.setText("Caducidad");
        jDialog13.getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, -1, -1));

        jLabel26.setText("Planta");
        jDialog13.getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, -1, -1));

        jLabel27.setText("Descuento");
        jDialog13.getContentPane().add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, -1, -1));

        jLabel28.setText("Marca");
        jDialog13.getContentPane().add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, -1, -1));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(660, 465));
        setPreferredSize(new java.awt.Dimension(670, 480));
        setSize(new java.awt.Dimension(660, 480));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/el_corte_ingles/news-8145-0284.jpg"))); // NOI18N
        getContentPane().add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 300, -1, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Fecha Tiempo Real");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 30, -1, -1));

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Hora Tiempo Real");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 10, -1, -1));

        jButton1.setBackground(new java.awt.Color(0, 204, 0));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("PLANTA 0");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, 80, 30));

        jButton2.setBackground(new java.awt.Color(0, 204, 0));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("PLANTA 1");
        jButton2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, 90, 30));

        jButton3.setBackground(new java.awt.Color(0, 204, 0));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("PLANTA 2");
        jButton3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 190, 80, 30));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/el_corte_ingles/salida.jpg"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 330, 60, 80));

        jButton15.setBackground(new java.awt.Color(0, 204, 0));
        jButton15.setForeground(new java.awt.Color(255, 255, 255));
        jButton15.setText("Personal");
        jButton15.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 382, 70, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/el_corte_ingles/Fondo_Progrmación.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -80, 670, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //Al pulsar botón, hacemos visible la pantalla
        jDialog2.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        jDialog1.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        //Salida del programa
        System.exit(0);
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        jDialog3.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        jDialog1.setVisible(false);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        
        jDialog4.setVisible(true);
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        jDialog5.setVisible(true);
        jDialog1.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        jDialog2.setVisible(false);
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        jDialog3.setVisible(false);
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        //Mensaje para asegurar si quiere o no cerrar el programa
        String[] botones = {"SI","NO"};
        int opcion = JOptionPane.showOptionDialog(null, "Seguro que quiere cerrar la aplicación?", "Cerrar Aplicación",0, JOptionPane.QUESTION_MESSAGE, null, botones,"SI");
        
        if(opcion == 0){
            System.exit(0);
        } else {
            JOptionPane.showMessageDialog(null, "Gracias por no cerrar la aplicación");
        }
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
         String[] botones = {"SI","NO"};
        int opcion = JOptionPane.showOptionDialog(null, "Seguro que quiere cerrar la aplicación?", "Cerrar Aplicación",0, JOptionPane.QUESTION_MESSAGE, null, botones,"SI");
        
        if(opcion == 0){
            System.exit(0);
        } else {
            JOptionPane.showMessageDialog(null, "Gracias por no cerrar la aplicación");
        }
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        String[] botones = {"SI","NO"};
        int opcion = JOptionPane.showOptionDialog(null, "Seguro que quiere cerrar la aplicación?", "Cerrar Aplicación",0, JOptionPane.QUESTION_MESSAGE, null, botones,"SI");
        
        if(opcion == 0){
            System.exit(0);
        } else {
            JOptionPane.showMessageDialog(null, "Gracias por no cerrar la aplicación");
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        jDialog6.setVisible(true);
        jDialog2.setVisible(false);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        jDialog7.setVisible(true);
        jDialog2.setVisible(false);
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        
        //Creamos los distintos usuarios para el control de acceso
        ArrayList<Usuario> usuarios = new ArrayList <>();
        
        //Añadimos usuarios con sus respectivas contraseñas
        usuarios.add(new Usuario("Adrian","1234"));
        usuarios.add(new Usuario("Santiago","1234"));
        usuarios.add(new Usuario("Carlota","1234"));
        usuarios.add(new Usuario("David","1234"));
        usuarios.add(new Usuario("Josep","1234"));
        
        //Guardamos la info en estas varibales
        String n = JOptionPane.showInputDialog("Ingresa tu nombre :");
        String c = JOptionPane.showInputDialog("Ingrese la clave :");
        
        boolean accesoPermitido = false;
        
        //Comprueba que el usuario ingresado existe y corresponde con su respectiva contraseña
        for(Usuario usuario:usuarios){
            if (usuario.getNombre().equals(n)&&usuario.getPassword().equals(c)){
                accesoPermitido=true;
                break;
            }  
        }
        
        if (accesoPermitido){
            
            JOptionPane.showMessageDialog(null, "Bienvenido a Personal : "+n);
            pantallaCrud.setVisible(true);
            
            
        }else{
           JOptionPane.showMessageDialog(null, "Datos incorrectos");
        }
        
        //Registra en un fichero de texto la consexión a personal con hora y fecha.
        FileWriter fw;
        
        try {
            fw = new FileWriter("C:\\test\\Registro_Inico_Sesion.txt", true);
            fw.write("\n" +  "Se han conectado a Personal   " + LocalTime.now() + " " + LocalDate.now());
            fw.close();
        } catch (IOException ex) {
            Logger.getLogger(Pantalla.class.getName()).log(Level.SEVERE, null, ex);
        }
            
            
  
   
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
                
        //Si el jRadioButton está seleccionado, acciona método tabla1
            
        jDialog8.setVisible(true);
            if(jRadioButton1.isSelected()){
                tabla1();
            }
                
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        
        //Establece la tabla del apartado Alimentación
        
        jDialog8.setVisible(true);
        DefaultTableModel modelo = new DefaultTableModel();
            modelo.addColumn("ID_Alimentacion");
            modelo.addColumn("Tipo");
            modelo.addColumn("Precio");
            modelo.addColumn("Caducidad");
            modelo.addColumn("Planta");
            modelo.addColumn("Descuento");
            modelo.addColumn("Marca");
            jTable1.setModel(modelo);
                String sql= "DELETE * FROM alimentacion";
                String datos[] = new String[7];
                Statement st;
            try {
                st = cn.createStatement();
                ResultSet rs = st.executeQuery(sql);
                while(rs.next()){
                    datos[0]=rs.getString(1);
                    datos[1]=rs.getString(2);
                    datos[2]=rs.getString(3);
                    datos[3]=rs.getString(4);
                    datos[4]=rs.getString(5);
                    datos[5]=rs.getString(6);
                    datos[6]=rs.getString(7);
                    modelo.addRow(datos);
                }
            jTable1.setModel(modelo);
            } catch (SQLException ex) {
                Logger.getLogger(Pantalla.class.getName()).log(Level.SEVERE, null, ex);
            }
  
    }//GEN-LAST:event_jButton18ActionPerformed

    
    private void jButton37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton37ActionPerformed
        
        //Hace que solo muestre los datos en la tabla si el botón insertar está seleccionado
        jDialog12.setVisible(true);
        if (jRadioButton2.isSelected()) {   
            tabla5();
        }
    }//GEN-LAST:event_jButton37ActionPerformed

    private void jButton38ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton38ActionPerformed
    
    //Establece la tabla del apartado Alimentación
    jDialog12.setVisible(true);
    DefaultTableModel modelo = new DefaultTableModel();
            modelo.addColumn("ID_Informatica");
            modelo.addColumn("Nombre");
            modelo.addColumn("Precio");
            modelo.addColumn("Marca");
            modelo.addColumn("Descuento");
            modelo.addColumn("Planta");
            modelo.addColumn("Dispositivo");
            jTable5.setModel(modelo);
                String sql= "DELETE * FROM Informatica";
                String datos[] = new String[7];
                Statement st;
            try {
                st = cn.createStatement();
                ResultSet rs = st.executeQuery(sql);
                while(rs.next()){
                    datos[0]=rs.getString(1);
                    datos[1]=rs.getString(2);
                    datos[2]=rs.getString(3);
                    datos[3]=rs.getString(4);
                    datos[4]=rs.getString(5);
                    datos[5]=rs.getString(6);
                    datos[6]=rs.getString(7);
                    modelo.addRow(datos);
                }
            jTable5.setModel(modelo);
            } catch (SQLException ex) {
                Logger.getLogger(Pantalla.class.getName()).log(Level.SEVERE, null, ex);
            }
        
    }//GEN-LAST:event_jButton38ActionPerformed

    private void jButton39ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton39ActionPerformed

    }//GEN-LAST:event_jButton39ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
       jDialog4.setVisible(false);
    }//GEN-LAST:event_jButton20ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        jDialog9.setVisible(true);
        if(jRadioButton3.isSelected()){
            tabla2();
        }
            
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        
        //Establece la tabla del apartado Alimentación
        jDialog9.setVisible(true);
        DefaultTableModel modelo = new DefaultTableModel();
            modelo.addColumn("ID_Maquillaje");
            modelo.addColumn("Nombre");
            modelo.addColumn("Tipo");
            modelo.addColumn("Precio");
            modelo.addColumn("Marca");
            modelo.addColumn("Descuento");
            modelo.addColumn("Promocion");
            modelo.addColumn("Color");
            modelo.addColumn("Tono");
            modelo.addColumn("Planta");
            modelo.addColumn("Descripcion");
            
            
            jTable2.setModel(modelo);
                String sql= "DELETE * FROM Maquillaje";
                String datos[] = new String[11];
                Statement st;
            try {
                st = cn.createStatement();
                ResultSet rs = st.executeQuery(sql);
                while(rs.next()){
                    datos[0]=rs.getString(1);
                    datos[1]=rs.getString(2);
                    datos[2]=rs.getString(3);
                    datos[3]=rs.getString(4);
                    datos[4]=rs.getString(5);
                    datos[5]=rs.getString(6);
                    datos[6]=rs.getString(7);
                    datos[7]=rs.getString(8);
                    datos[8]=rs.getString(9);
                    datos[9]=rs.getString(10);
                    datos[10]=rs.getString(11);
                    modelo.addRow(datos);
                }
            jTable2.setModel(modelo);
            } catch (SQLException ex) {
                Logger.getLogger(Pantalla.class.getName()).log(Level.SEVERE, null, ex);
            }
        
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton25ActionPerformed
        jDialog5.setVisible(false);
    }//GEN-LAST:event_jButton25ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
        
        jDialog10.setVisible(true);
        if(jRadioButton4.isSelected()){
            tabla3();
            
        }
    }//GEN-LAST:event_jButton21ActionPerformed

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
        
        //Establece la tabla del apartado Ropa
        jDialog10.setVisible(true);
        DefaultTableModel modelo = new DefaultTableModel();
            modelo.addColumn("ID_Ropa");
            modelo.addColumn("Nombre");
            modelo.addColumn("Tipo");
            modelo.addColumn("Precio");
            modelo.addColumn("Marca");
            modelo.addColumn("Descuento");
            modelo.addColumn("Promocion");
            modelo.addColumn("Color");
            modelo.addColumn("Codigo");
            modelo.addColumn("Planta");
            jTable3.setModel(modelo);
                String sql= "SELECT * FROM Ropa";
                String datos[] = new String[10];
                Statement st;
            try {
                st = cn.createStatement();
                ResultSet rs = st.executeQuery(sql);
                while(rs.next()){
                    datos[0]=rs.getString(1);
                    datos[1]=rs.getString(2);
                    datos[2]=rs.getString(3);
                    datos[3]=rs.getString(4);
                    datos[4]=rs.getString(5);
                    datos[5]=rs.getString(6);
                    datos[6]=rs.getString(7);
                    datos[7]=rs.getString(8);
                    datos[8]=rs.getString(9);
                    datos[9]=rs.getString(10);
                    modelo.addRow(datos);
                }
            jTable3.setModel(modelo);
            } catch (SQLException ex) {
                Logger.getLogger(Pantalla.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_jButton22ActionPerformed

    private void jButton30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton30ActionPerformed
        jDialog6.setVisible(false);
    }//GEN-LAST:event_jButton30ActionPerformed

    private void jButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton23ActionPerformed
        jDialog11.setVisible(true);
        if(jRadioButton5.isSelected()){
            tabla4();
        }
            
        
    }//GEN-LAST:event_jButton23ActionPerformed

    private void jButton24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton24ActionPerformed
        
        //Establece la tabla del apartado Calzado
        jDialog11.setVisible(true);
        DefaultTableModel modelo = new DefaultTableModel();
            modelo.addColumn("ID_Calzado");
            modelo.addColumn("Nombre");
            modelo.addColumn("Tipo");
            modelo.addColumn("Precio");
            modelo.addColumn("Marca");
            modelo.addColumn("Descuento");
            modelo.addColumn("Promocion");
            modelo.addColumn("Color");
            modelo.addColumn("Codigo");
            modelo.addColumn("Planta");
            jTable4.setModel(modelo);
                String sql= "DELETE * FROM Calzado";
                String datos[] = new String[10];
                Statement st;
            try {
                st = cn.createStatement();
                ResultSet rs = st.executeQuery(sql);
                while(rs.next()){
                    datos[0]=rs.getString(1);
                    datos[1]=rs.getString(2);
                    datos[2]=rs.getString(3);
                    datos[3]=rs.getString(4);
                    datos[4]=rs.getString(5);
                    datos[5]=rs.getString(6);
                    datos[6]=rs.getString(7);
                    datos[7]=rs.getString(8);
                    datos[8]=rs.getString(9);
                    datos[9]=rs.getString(10);
                    modelo.addRow(datos);
                }
            jTable4.setModel(modelo);
            } catch (SQLException ex) {
                Logger.getLogger(Pantalla.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_jButton24ActionPerformed

    private void jButton35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton35ActionPerformed
        jDialog7.setVisible(false);
    }//GEN-LAST:event_jButton35ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    /**
     *
     */
    public void tabla1(){
        
    //Crea objeto tipo DefaultTableModel
    DefaultTableModel modelo = new DefaultTableModel();
            //Añade las columnas correspondientes:
            modelo.addColumn("ID_Alimentacion");
            modelo.addColumn("tipo");
            modelo.addColumn("precio");
            modelo.addColumn("caducidad");
            modelo.addColumn("planta");
            modelo.addColumn("descuento");
            modelo.addColumn("marca");
            
            //Establece en jTaabble1 el modelo diseñado anteriormente
            jTable1.setModel(modelo);
                String sql= "SELECT * FROM alimentacion";
                String datos[] = new String[7];
                Statement st;
            try {
                st = cn.createStatement();
                ResultSet rs = st.executeQuery(sql);
                while(rs.next()){
                    datos[0]=rs.getString(1);
                    datos[1]=rs.getString(2);
                    datos[2]=rs.getString(3);
                    datos[3]=rs.getString(4);
                    datos[4]=rs.getString(5);
                    datos[5]=rs.getString(6);
                    datos[6]=rs.getString(7);
                    modelo.addRow(datos);
                }
            jTable1.setModel(modelo);
            } catch (SQLException ex) {
                Logger.getLogger(Pantalla.class.getName()).log(Level.SEVERE, null, ex);
            }
}

    /**
     *
     */
    public void tabla2(){
    DefaultTableModel modelo = new DefaultTableModel();
            modelo.addColumn("ID_Maquillaje");
            modelo.addColumn("Nombre");
            modelo.addColumn("Tipo");
            modelo.addColumn("Precio");
            modelo.addColumn("Marca");
            modelo.addColumn("Descuento");
            modelo.addColumn("Promocion");
            modelo.addColumn("Color");
            modelo.addColumn("Tono");
            modelo.addColumn("Planta");
            modelo.addColumn("Descripcion");
            
            
            jTable2.setModel(modelo);
                String sql= "SELECT * FROM Maquillaje";
                String datos[] = new String[11];
                Statement st;
            try {
                st = cn.createStatement();
                ResultSet rs = st.executeQuery(sql);
                while(rs.next()){
                    datos[0]=rs.getString(1);
                    datos[1]=rs.getString(2);
                    datos[2]=rs.getString(3);
                    datos[3]=rs.getString(4);
                    datos[4]=rs.getString(5);
                    datos[5]=rs.getString(6);
                    datos[6]=rs.getString(7);
                    datos[7]=rs.getString(8);
                    datos[8]=rs.getString(9);
                    datos[9]=rs.getString(10);
                    datos[10]=rs.getString(11);
                    modelo.addRow(datos);
                }
            jTable2.setModel(modelo);
            } catch (SQLException ex) {
                Logger.getLogger(Pantalla.class.getName()).log(Level.SEVERE, null, ex);
            }
}

    /**
     *
     */
    public void tabla3(){
    DefaultTableModel modelo = new DefaultTableModel();
            modelo.addColumn("ID_Ropa");
            modelo.addColumn("Nombre");
            modelo.addColumn("Tipo");
            modelo.addColumn("Precio");
            modelo.addColumn("Marca");
            modelo.addColumn("Descuento");
            modelo.addColumn("Promocion");
            modelo.addColumn("Color");
            modelo.addColumn("Codigo");
            modelo.addColumn("Planta");
            jTable3.setModel(modelo);
                String sql= "SELECT * FROM Ropa";
                String datos[] = new String[10];
                Statement st;
            try {
                st = cn.createStatement();
                ResultSet rs = st.executeQuery(sql);
                while(rs.next()){
                    datos[0]=rs.getString(1);
                    datos[1]=rs.getString(2);
                    datos[2]=rs.getString(3);
                    datos[3]=rs.getString(4);
                    datos[4]=rs.getString(5);
                    datos[5]=rs.getString(6);
                    datos[6]=rs.getString(7);
                    datos[7]=rs.getString(8);
                    datos[8]=rs.getString(9);
                    datos[9]=rs.getString(10);
                    modelo.addRow(datos);
                }
            jTable3.setModel(modelo);
            } catch (SQLException ex) {
                Logger.getLogger(Pantalla.class.getName()).log(Level.SEVERE, null, ex);
            }
}

    /**
     *
     */
    public void tabla4(){
    DefaultTableModel modelo = new DefaultTableModel();
            modelo.addColumn("ID_Calzado");
            modelo.addColumn("Nombre");
            modelo.addColumn("Tipo");
            modelo.addColumn("Precio");
            modelo.addColumn("Marca");
            modelo.addColumn("Descuento");
            modelo.addColumn("Promocion");
            modelo.addColumn("Color");
            modelo.addColumn("Codigo");
            modelo.addColumn("Planta");
            jTable4.setModel(modelo);
                String sql= "SELECT * FROM Calzado";
                String datos[] = new String[10];
                Statement st;
            try {
                st = cn.createStatement();
                ResultSet rs = st.executeQuery(sql);
                while(rs.next()){
                    datos[0]=rs.getString(1);
                    datos[1]=rs.getString(2);
                    datos[2]=rs.getString(3);
                    datos[3]=rs.getString(4);
                    datos[4]=rs.getString(5);
                    datos[5]=rs.getString(6);
                    datos[6]=rs.getString(7);
                    datos[7]=rs.getString(8);
                    datos[8]=rs.getString(9);
                    datos[9]=rs.getString(10);
                    modelo.addRow(datos);
                }
            jTable4.setModel(modelo);
            } catch (SQLException ex) {
                Logger.getLogger(Pantalla.class.getName()).log(Level.SEVERE, null, ex);
            }
}

    /**
     *
     */
    public void tabla5(){
DefaultTableModel modelo = new DefaultTableModel();
            modelo.addColumn("ID_Informatica");
            modelo.addColumn("Nombre");
            modelo.addColumn("Precio");
            modelo.addColumn("Marca");
            modelo.addColumn("Descuento");
            modelo.addColumn("Planta");
            modelo.addColumn("Dispositivo");
            jTable5.setModel(modelo);
                String sql= "SELECT * FROM Informatica";
                String datos[] = new String[7];
                Statement st;
            try {
                st = cn.createStatement();
                ResultSet rs = st.executeQuery(sql);
                while(rs.next()){
                    datos[0]=rs.getString(1);
                    datos[1]=rs.getString(2);
                    datos[2]=rs.getString(3);
                    datos[3]=rs.getString(4);
                    datos[4]=rs.getString(5);
                    datos[5]=rs.getString(6);
                    datos[6]=rs.getString(7);
                    modelo.addRow(datos);
                }
            jTable5.setModel(modelo);
            } catch (SQLException ex) {
                Logger.getLogger(Pantalla.class.getName()).log(Level.SEVERE, null, ex);
            }
}

    /**
     *
     */
    public void insertar(){
    tabla1();
    int fila = jTable1.getSelectedRow();
    if (fila >= 0) {
        try {
            // Obtener los nuevos valores de los JTextField
            String idAlimentacion = jTextField1.getText();
            String tipo = jTextField2.getText();
            String precio = jTextField3.getText();
            String caducidad = jTextField4.getText();
            String planta = jTextField5.getText();
            String descuento = jTextField6.getText();
            String marca = jTextField7.getText();

            // Preparar la sentencia SQL UPDATE
            String sql = "UPDATE alimentacion SET ID_Alimentacion=?, Tipo=?, Precio=?, Caducidad=?, Planta=?, Descuento=?, Marca=? WHERE ID_Alimentacion=?";
            PreparedStatement statement = cn.prepareStatement(sql);
            statement.setString(1, idAlimentacion);
            statement.setString(2, tipo);
            statement.setString(3, precio);
            statement.setString(4, caducidad);
            statement.setString(5, planta);
            statement.setString(6, descuento);
            statement.setString(7, marca);
            statement.setString(8, jTable1.getValueAt(fila, 0).toString()); // ID_Alimentacion original

            // Ejecutar la sentencia UPDATE
            int filasActualizadas = statement.executeUpdate();
            
            // Verificar si la actualización fue exitosa
            if (filasActualizadas > 0) {
                JOptionPane.showMessageDialog(null, "La fila se actualizó correctamente.");
            } else {
                JOptionPane.showMessageDialog(null, "Error al actualizar la fila.");
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error al actualizar la fila: " + ex.getMessage());
        }
    } else {
        JOptionPane.showMessageDialog(null, "Fila no seleccionada.");
    }

}


    Timer timer = new Timer (100, new ActionListener (){

    @Override
    public void actionPerformed(ActionEvent e){
       //mostrar hora en un label
        jLabel11.setText(String.valueOf(LocalTime.now()));
        jLabel2.setText(String.valueOf(LocalDate.now()));
    }
    });

    /**
     *
     * @param args
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pantalla().setVisible(true);
                 
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton35;
    private javax.swing.JButton jButton37;
    private javax.swing.JButton jButton38;
    private javax.swing.JButton jButton39;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialog10;
    private javax.swing.JDialog jDialog11;
    private javax.swing.JDialog jDialog12;
    private javax.swing.JDialog jDialog13;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JDialog jDialog3;
    private javax.swing.JDialog jDialog4;
    private javax.swing.JDialog jDialog5;
    private javax.swing.JDialog jDialog6;
    private javax.swing.JDialog jDialog7;
    private javax.swing.JDialog jDialog8;
    private javax.swing.JDialog jDialog9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JTable jTable5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    // End of variables declaration//GEN-END:variables
}
